$ErrorActionPreference = "Stop"

Write-Output "Waiting for GatewayAPI on port 8383..."
while (!(Test-NetConnection localhost -Port 8383 -InformationLevel Quiet)) { Start-Sleep -Seconds 2 }
Write-Output "GatewayAPI is UP! Waiting 15s for Eureka to settle..."
Start-Sleep -Seconds 15

$headers = @{ "Content-Type" = "application/json" }

Write-Output "`n==============================================="
Write-Output "       COMPREHENSIVE API TEST SUITE            "
Write-Output "==============================================="

# 1. Register a TOURIST user
Write-Output "`n[1] Testing TOURIST Registration (Triggers Tourist Sync & Audit Timestamps)"
$touristEmail = "tourist.test" + (Get-Date -UFormat "%s") + "@tourismgov.com"
$registerBody = @{ "name"="Tourist User"; "email"=$touristEmail; "password"="Password123!"; "role"="TOURIST"; "phone"="9876543210" } | ConvertTo-Json
try {
    $regRes = Invoke-RestMethod -Method Post -Uri "http://localhost:8383/tourismgov/v1/auth/register" -Headers $headers -Body $registerBody
    Write-Output "RESULT: SUCCESS"
    Write-Output "User Created At: $($regRes.createdAt)"
    Write-Output "User Updated At: $($regRes.updatedAt)"
} catch {
    Write-Output "RESULT: FAILED - $_"
}

# 2. Login as TOURIST
Write-Output "`n[2] Testing Login as TOURIST"
$loginBody = @{ "email"=$touristEmail; "password"="Password123!" } | ConvertTo-Json
try {
    $loginRes = Invoke-RestMethod -Method Post -Uri "http://localhost:8383/tourismgov/v1/auth/login" -Headers $headers -Body $loginBody
    $touristToken = $loginRes.token
    Write-Output "RESULT: SUCCESS (Token retrieved)"
} catch {
    Write-Output "RESULT: FAILED - $_"
}

# 3. Test Report API (Should fail with 403 Forbidden)
Write-Output "`n[3] Testing Report API Edge Case (Tourist attempting to generate report)"
$touristHeaders = @{ "Authorization" = "Bearer $touristToken"; "Content-Type" = "application/json" }
$reportBody = @{ "scope"="SITE" } | ConvertTo-Json
try {
    $reportRes = Invoke-RestMethod -Method Post -Uri "http://localhost:8383/tourismgov/v1/reports/generate" -Headers $touristHeaders -Body $reportBody
    Write-Output "RESULT: FAILED (Expected 403, but got 200 OK)"
} catch {
    $status = $_.Exception.Response.StatusCode.value__
    if ($status -eq 403) {
        Write-Output "RESULT: SUCCESS (Correctly blocked with 403 Forbidden)"
    } else {
        Write-Output "RESULT: UNEXPECTED ERROR - Status $status"
    }
}

# 4. Register an ADMIN user
Write-Output "`n[4] Testing ADMIN Registration"
$adminEmail = "admin.test" + (Get-Date -UFormat "%s") + "@tourismgov.com"
$adminRegBody = @{ "name"="Admin User"; "email"=$adminEmail; "password"="Password123!"; "role"="ADMIN"; "phone"="9876543211" } | ConvertTo-Json
try {
    $adminRegRes = Invoke-RestMethod -Method Post -Uri "http://localhost:8383/tourismgov/v1/auth/register" -Headers $headers -Body $adminRegBody
    Write-Output "RESULT: SUCCESS"
} catch {
    Write-Output "RESULT: FAILED - $_"
}

# 5. Login as ADMIN
Write-Output "`n[5] Testing Login as ADMIN"
$adminLoginBody = @{ "email"=$adminEmail; "password"="Password123!" } | ConvertTo-Json
try {
    $adminLoginRes = Invoke-RestMethod -Method Post -Uri "http://localhost:8383/tourismgov/v1/auth/login" -Headers $headers -Body $adminLoginBody
    $adminToken = $adminLoginRes.token
    Write-Output "RESULT: SUCCESS (Token retrieved)"
} catch {
    Write-Output "RESULT: FAILED - $_"
}

# 6. Generate Report as ADMIN
Write-Output "`n[6] Testing Report Generation (Happy Path)"
$adminHeaders = @{ "Authorization" = "Bearer $adminToken"; "Content-Type" = "application/json" }
try {
    $reportRes = Invoke-RestMethod -Method Post -Uri "http://localhost:8383/tourismgov/v1/reports/generate" -Headers $adminHeaders -Body $reportBody
    Write-Output "RESULT: SUCCESS"
    Write-Output "Report ID: $($reportRes.reportId)"
    Write-Output "Generated By: $($reportRes.generatedByName) ($($reportRes.generatedByRole))"
} catch {
    Write-Output "RESULT: FAILED - $_"
}

# 7. Check Notifications for ADMIN (Should contain "Report Generated")
Write-Output "`n[7] Testing Notification Delivery"
Start-Sleep -Seconds 3 # Wait for async notification to land
try {
    $notifRes = Invoke-RestMethod -Method Get -Uri "http://localhost:8383/tourismgov/v1/notifications" -Headers $adminHeaders
    if ($notifRes.Length -gt 0) {
        Write-Output "RESULT: SUCCESS ($($notifRes.Length) notifications found)"
        Write-Output "Latest Notification Subject: $($notifRes[0].subject)"
    } else {
        Write-Output "RESULT: FAILED (No notifications found)"
    }
} catch {
    Write-Output "RESULT: FAILED - $_"
}

Write-Output "`n==============================================="
Write-Output "              TEST SUITE COMPLETE              "
Write-Output "==============================================="
